### ISSUE TITLE
FILE MISSING

### ISSUE THREAD

**Issue by Rushali03** [scaffold-eth/scaffold-eth-examples#34]
Please provide assests.js file

**Comment by aggprakhar** [comment]
I am facing the same error

```
Failed to compile
./src/App.jsx
Module not found: Can't resolve './assets.js' in '~/scaffold-eth-examples/packages/react-app/src'
This error occurred during the build time and cannot be dismissed.
```

**Comment by RohinJoshi1** [comment]
Was anyone able to find a workaround for the assets.js file missing issue:
Module not found: Can't resolve './assets.js' in '~/scaffold-eth-examples/packages/react-app/src'
This error occurred during the build time and cannot be dismissed.
